In [1]:
import pandas as pd
import numpy as np
import scanpy as sc

In [2]:
sc_gene_list=pd.read_excel('sc_gene_list.xlsx', engine='openpyxl',index_col=0,header=None)
Col_Listname=list(sc_gene_list.index)


In [3]:
from collections import Counter
Counter(Col_Listname).most_common(15)



[('ccdc13', 2),
 ('pdzd7', 2),
 ('cbarp', 2),
 ('wnk1', 2),
 ('nek10', 2),
 ('kif26b', 2),
 ('usp54', 2),
 ('cdhr4', 2),
 ('vwa5b2', 2),
 ('snx29', 2),
 ('zglp1', 1),
 ('vmn2r65', 1),
 ('gm10024', 1),
 ('oog3', 1),
 ('ldlrap1', 1)]

In [4]:
df = pd.read_csv('bone_marrow_cell.csv', index_col=0)


In [5]:
df.columns=Col_Listname

df.loc[:,(df==0).all()].columns

Index(['gm20852'], dtype='object')

In [6]:
del df['gm20852']


In [7]:
df

zglp1    vmn2r65  gm10024      oog3  \
GSE41265_GSM1012788_SRR578581    0.085863   0.053987      0.0  0.000000   
GSE41265_GSM1110889_SRR799683    7.412014   0.063840      0.0  0.000000   
GSE41265_GSM1110890_SRR799684    0.000000  12.037643      0.0  0.039253   
GSE41265_GSM1110890_SRR799685    0.000000  12.488104      0.0  0.000000   
GSE41265_GSM1110891_SRR799686    0.000000   0.046583      0.0  0.000000   
...                                   ...        ...      ...       ...   
GSE81682_GSM2170276_SRR3560095   6.445299   0.000000      0.0  0.000000   
GSE81682_GSM2170277_SRR3560096  24.122951   0.000000      0.0  0.000000   
GSE81682_GSM2170282_SRR3560101  44.858982   0.000000      0.0  0.000000   
GSE81682_GSM2170284_SRR3560103  10.777650   0.000000      0.0  0.000000   
GSE86929_GSM2310415_SRR4242632   4.044559   0.930375      0.0  0.000000   

                                  ldlrap1      mdn1     ifi208       wfdc17  \
GSE41265_GSM1012788_SRR578581    0.000000  0.788288   0.077623     5.670716   
GSE41265_GSM1110889_SRR799683    0.000000  0.179636   0.642533  1846.187044   
GSE41265_GSM1110890_SRR799684    0.000000  0.102503  14.601501  3540.700090   
GSE41265_GSM1110890_SRR799685    0.000000  0.157862  12.949241  3602.986494   
GSE41265_GSM1110891_SRR799686    0.000000  2.695954  23.475915  2014.659753   
...                                   ...       ...        ...          ...   
GSE81682_GSM2170276_SRR3560095   0.429903  2.584064   0.000000     3.446730   
GSE81682_GSM2170277_SRR3560096   0.000000  0.946719   0.000000    13.447795   
GSE81682_GSM2170282_SRR3560101  11.885296  1.638539   0.000000     2.165681   
GSE81682_GSM2170284_SRR3560103   0.000000  2.245448   0.000000     0.000000   
GSE86929_GSM2310415_SRR4242632   0.256613  0.931604   0.468199   462.226416   

                                    mfap1b   tmsb15b2  ...    clca4b  \
GSE41265_GSM1012788_SRR578581   315.864386   0.000000  ...  0.000000   
GSE41265_GSM1110889_SRR799683   103.104245  23.771005  ...  0.000000   
GSE41265_GSM1110890_SRR799684    22.899794   0.432650  ...  0.000000   
GSE41265_GSM1110890_SRR799685    25.244305   0.623322  ...  0.061340   
GSE41265_GSM1110891_SRR799686    47.655663   0.000000  ...  0.000000   
...                                    ...        ...  ...       ...   
GSE81682_GSM2170276_SRR3560095   18.034300   0.000000  ...  0.000000   
GSE81682_GSM2170277_SRR3560096   18.487480   0.000000  ...  0.000000   
GSE81682_GSM2170282_SRR3560101    9.442897   3.646625  ...  0.358857   
GSE81682_GSM2170284_SRR3560103    0.466707   0.000000  ...  0.000000   
GSE86929_GSM2310415_SRR4242632    5.681451   0.000000  ...  0.014205   

                                    cept1       taf13     kcnc4     tmem56  \
GSE41265_GSM1012788_SRR578581    0.219942    0.921119  0.000000   0.000000   
GSE41265_GSM1110889_SRR799683   64.956231    0.000000  3.090357   0.097965   
GSE41265_GSM1110890_SRR799684   89.988372   23.948507  0.000000   0.000000   
GSE41265_GSM1110890_SRR799685   94.660704   21.478569  0.000000   0.000000   
GSE41265_GSM1110891_SRR799686   86.540135    0.317922  0.000000   9.650364   
...                                   ...         ...       ...        ...   
GSE81682_GSM2170276_SRR3560095   0.952495  106.374822  0.000000   3.348550   
GSE81682_GSM2170277_SRR3560096  18.216986    0.000000  0.000000   0.000000   
GSE81682_GSM2170282_SRR3560101  20.348342   37.429507  0.000000  12.623952   
GSE81682_GSM2170284_SRR3560103  80.357348    0.000000  0.000000   0.000000   
GSE86929_GSM2310415_SRR4242632   7.517548    8.571986  0.062552   0.571081   

                                   arfip1     prmt6     ifi44     tiparp  \
GSE41265_GSM1012788_SRR578581    1.408526  0.000000  0.054158   0.138846   
GSE41265_GSM1110889_SRR799683    0.000000  0.000000  0.000000   3.324802   
GSE41265_GSM1110890_SRR799684    0.115486  0.000000  0.046625   8.785713   
GSE41265_GSM1110890_SRR799685    0.000000  0.000000  0.067173  11.667424   
GSE4

In [8]:
Gene_pair_True= pd.read_csv('filter_data.txt', sep='\t', header=None)
Gene_pair_True.columns = ['geneA','geneB','value']
Gene_pair_True

geneA   geneB  value
0      bcl6    il1a      1
1      bcl6    ebi3      0
2      bcl6  gtf2e2      1
3      bcl6  mogat2      0
4      bcl6   ston2      1
...     ...     ...    ...
53497  mafb    rer1      0
53498  mafb     prn      1
53499  mafb   ubtd2      0
53500  mafb  inpp5a      1
53501  mafb  sema4g      0

[53502 rows x 3 columns]

In [9]:

S1=Gene_pair_True['geneA'].unique().tolist()
S1
# for i in range(len(S1)):
#     print(S1[i] in HvgsData.columns.to_list())


['bcl6',
 'stat1',
 'nr3c1',
 'rela',
 'foxo3',
 'ncor2',
 'ncor1',
 'stat6',
 'junb',
 'stat2',
 'srf',
 'smad3',
 'mafb']

In [10]:
df_TF=df[S1]
df_TF

bcl6       stat1      nr3c1       rela  \
GSE41265_GSM1012788_SRR578581   0.000000   10.533667   0.720656  52.959586   
GSE41265_GSM1110889_SRR799683   0.000000  115.562026   4.022323  15.976900   
GSE41265_GSM1110890_SRR799684   0.000000   82.062006   0.074450  15.472971   
GSE41265_GSM1110890_SRR799685   0.000000   82.770504   0.035754  18.050859   
GSE41265_GSM1110891_SRR799686   0.473802  178.210528   5.347746   7.772105   
...                                  ...         ...        ...        ...   
GSE81682_GSM2170276_SRR3560095  0.000000   19.161209   8.821797  29.135278   
GSE81682_GSM2170277_SRR3560096  1.112924    4.437966   6.952604  17.462876   
GSE81682_GSM2170282_SRR3560101  0.000000    6.406364  20.289445  16.339727   
GSE81682_GSM2170284_SRR3560103  0.000000    0.272956  32.047876  43.369873   
GSE86929_GSM2310415_SRR4242632  0.742189    1.311642   2.218930   2.084062   

                                    foxo3      ncor2       ncor1      stat6  \
GSE41265_GSM1012788_SRR578581    0.000000  10.799669    5.905564   0.274156   
GSE41265_GSM1110889_SRR799683    0.000000   0.000000    0.186224  28.853214   
GSE41265_GSM1110890_SRR799684    0.000000   0.000000    5.626441  23.437019   
GSE41265_GSM1110890_SRR799685    0.000000   0.000000    4.590178  25.740975   
GSE41265_GSM1110891_SRR799686    2.543766   0.026324   22.081445   4.660235   
...                                   ...        ...         ...        ...   
GSE81682_GSM2170276_SRR3560095   2.934933   0.939504   92.297315   0.316607   
GSE81682_GSM2170277_SRR3560096   0.449057   1.724979  231.028485  14.532668   
GSE81682_GSM2170282_SRR3560101   0.983522   0.000000   90.274969   4.177601   
GSE81682_GSM2170284_SRR3560103  16.709594   2.461722   45.182407   0.491606   
GSE86929_GSM2310415_SRR4242632   1.245789   0.070100   42.247159   1.007925   

                                     junb      stat2        srf      smad3  \
GSE41265_GSM1012788_SRR578581    0.066100  28.249785   0.000000   0.053859   
GSE41265_GSM1110889_SRR799683   10.473955  36.790521   0.000000  20.635255   
GSE41265_GSM1110890_SRR799684   11.893267  21.491949   0.000000   0.000000   
GSE41265_GSM1110890_SRR799685   11.559791  23.307614   0.000000   0.000000   
GSE41265_GSM1110891_SRR799686   15.228411  21.154344   0.000000   0.046473   
...                                   ...        ...        ...        ...   
GSE81682_GSM2170276_SRR3560095   3.816737   0.287437  11.776709   0.621987   
GSE81682_GSM2170277_SRR3560096   9.110043   0.065969   0.000000   0.142750   
GSE81682_GSM2170282_SRR3560101   6.714868   0.000000   0.000000   3.908124   
GSE81682_GSM2170284_SRR3560103   0.000000   0.669468   0.000000   0.000000   
GSE86929_GSM2310415_SRR4242632   0.721445   1.558462   0.312428   5.043086   

                                    mafb  
GSE41265_GSM1012788_SRR578581   0.000000  
GSE41265_GSM1110889_SRR799683   0.000000  
GSE41265_GSM1110890_SRR799684   0.000000  
GSE41265_GSM1110890_SRR799685   0.000000  
GSE41265_GSM1110891_SRR799686   0.000000  
...                                  ...  
GSE81682_GSM2170276_SRR3560095  0.000000  
GSE81682_GSM2170277_SRR3560096  0.000000  
GSE81682_GSM2170282_SRR3560101  0.000000  
GSE81682_GSM2170284_SRR3560103  0.000000  
GSE86929_GSM2310415_SRR4242632  0.485213  

[6283 rows x 13 columns]

In [11]:
df.drop(columns=S1,inplace=True)


In [12]:
df

zglp1    vmn2r65  gm10024      oog3  \
GSE41265_GSM1012788_SRR578581    0.085863   0.053987      0.0  0.000000   
GSE41265_GSM1110889_SRR799683    7.412014   0.063840      0.0  0.000000   
GSE41265_GSM1110890_SRR799684    0.000000  12.037643      0.0  0.039253   
GSE41265_GSM1110890_SRR799685    0.000000  12.488104      0.0  0.000000   
GSE41265_GSM1110891_SRR799686    0.000000   0.046583      0.0  0.000000   
...                                   ...        ...      ...       ...   
GSE81682_GSM2170276_SRR3560095   6.445299   0.000000      0.0  0.000000   
GSE81682_GSM2170277_SRR3560096  24.122951   0.000000      0.0  0.000000   
GSE81682_GSM2170282_SRR3560101  44.858982   0.000000      0.0  0.000000   
GSE81682_GSM2170284_SRR3560103  10.777650   0.000000      0.0  0.000000   
GSE86929_GSM2310415_SRR4242632   4.044559   0.930375      0.0  0.000000   

                                  ldlrap1      mdn1     ifi208       wfdc17  \
GSE41265_GSM1012788_SRR578581    0.000000  0.788288   0.077623     5.670716   
GSE41265_GSM1110889_SRR799683    0.000000  0.179636   0.642533  1846.187044   
GSE41265_GSM1110890_SRR799684    0.000000  0.102503  14.601501  3540.700090   
GSE41265_GSM1110890_SRR799685    0.000000  0.157862  12.949241  3602.986494   
GSE41265_GSM1110891_SRR799686    0.000000  2.695954  23.475915  2014.659753   
...                                   ...       ...        ...          ...   
GSE81682_GSM2170276_SRR3560095   0.429903  2.584064   0.000000     3.446730   
GSE81682_GSM2170277_SRR3560096   0.000000  0.946719   0.000000    13.447795   
GSE81682_GSM2170282_SRR3560101  11.885296  1.638539   0.000000     2.165681   
GSE81682_GSM2170284_SRR3560103   0.000000  2.245448   0.000000     0.000000   
GSE86929_GSM2310415_SRR4242632   0.256613  0.931604   0.468199   462.226416   

                                    mfap1b   tmsb15b2  ...    clca4b  \
GSE41265_GSM1012788_SRR578581   315.864386   0.000000  ...  0.000000   
GSE41265_GSM1110889_SRR799683   103.104245  23.771005  ...  0.000000   
GSE41265_GSM1110890_SRR799684    22.899794   0.432650  ...  0.000000   
GSE41265_GSM1110890_SRR799685    25.244305   0.623322  ...  0.061340   
GSE41265_GSM1110891_SRR799686    47.655663   0.000000  ...  0.000000   
...                                    ...        ...  ...       ...   
GSE81682_GSM2170276_SRR3560095   18.034300   0.000000  ...  0.000000   
GSE81682_GSM2170277_SRR3560096   18.487480   0.000000  ...  0.000000   
GSE81682_GSM2170282_SRR3560101    9.442897   3.646625  ...  0.358857   
GSE81682_GSM2170284_SRR3560103    0.466707   0.000000  ...  0.000000   
GSE86929_GSM2310415_SRR4242632    5.681451   0.000000  ...  0.014205   

                                    cept1       taf13     kcnc4     tmem56  \
GSE41265_GSM1012788_SRR578581    0.219942    0.921119  0.000000   0.000000   
GSE41265_GSM1110889_SRR799683   64.956231    0.000000  3.090357   0.097965   
GSE41265_GSM1110890_SRR799684   89.988372   23.948507  0.000000   0.000000   
GSE41265_GSM1110890_SRR799685   94.660704   21.478569  0.000000   0.000000   
GSE41265_GSM1110891_SRR799686   86.540135    0.317922  0.000000   9.650364   
...                                   ...         ...       ...        ...   
GSE81682_GSM2170276_SRR3560095   0.952495  106.374822  0.000000   3.348550   
GSE81682_GSM2170277_SRR3560096  18.216986    0.000000  0.000000   0.000000   
GSE81682_GSM2170282_SRR3560101  20.348342   37.429507  0.000000  12.623952   
GSE81682_GSM2170284_SRR3560103  80.357348    0.000000  0.000000   0.000000   
GSE86929_GSM2310415_SRR4242632   7.517548    8.571986  0.062552   0.571081   

                                   arfip1     prmt6     ifi44     tiparp  \
GSE41265_GSM1012788_SRR578581    1.408526  0.000000  0.054158   0.138846   
GSE41265_GSM1110889_SRR799683    0.000000  0.000000  0.000000   3.324802   
GSE41265_GSM1110890_SRR799684    0.115486  0.000000  0.046625   8.785713   
GSE41265_GSM1110890_SRR799685    0.000000  0.000000  0.067173  11.667424   
GSE4

In [39]:
cellinfo = pd.DataFrame(df.index,index=df.index,columns=['sample_index'])
geneinfo = pd.DataFrame(df.columns,index=df.columns,columns=['genes_index'])
sce = sc.AnnData(df, obs=cellinfo, var = geneinfo)
sce.var_names_make_unique()

# sc.pp.normalize_total(sce) # 不要和log顺序搞反了 ，这个是去文库的
# sc.pp.log1p(sce)

sc.pp.highly_variable_genes(sce,flavor='seurat_v3',n_top_genes=987)
sce = sce[:, sce.var.highly_variable]
HvgsData=sce.to_df()
HvgsData

/tmp/ipykernel_269028/3950805107.py:3: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  sce = sc.AnnData(df, obs=cellinfo, var = geneinfo)
/home/dreameryty/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/dreameryty/.local/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


gm10024   tmsb15b2  spink13  7420461p10rik  \
GSE41265_GSM1012788_SRR578581       0.0   0.000000      0.0      46.150230   
GSE41265_GSM1110889_SRR799683       0.0  23.771006      0.0       0.000000   
GSE41265_GSM1110890_SRR799684       0.0   0.432650      0.0       0.000000   
GSE41265_GSM1110890_SRR799685       0.0   0.623322      0.0       0.000000   
GSE41265_GSM1110891_SRR799686       0.0   0.000000      0.0       0.000000   
...                                 ...        ...      ...            ...   
GSE81682_GSM2170276_SRR3560095      0.0   0.000000      0.0       0.000000   
GSE81682_GSM2170277_SRR3560096      0.0   0.000000      0.0       0.000000   
GSE81682_GSM2170282_SRR3560101      0.0   3.646625      0.0       0.000000   
GSE81682_GSM2170284_SRR3560103      0.0   0.000000      0.0       0.000000   
GSE86929_GSM2310415_SRR4242632      0.0   0.000000      0.0       1.100798   

                                gm10731    gm2042      cphx2      cphx3  \
GSE41265_GSM1012788_SRR578581       0.0  0.260867   0.000000   0.000000   
GSE41265_GSM1110889_SRR799683       0.0  0.000000   0.000000   0.000000   
GSE41265_GSM1110890_SRR799684       0.0  0.000000   0.323892   0.323892   
GSE41265_GSM1110890_SRR799685       0.0  0.000000   0.000000   0.155545   
GSE41265_GSM1110891_SRR799686       0.0  0.000000  16.015079  16.015079   
...                                 ...       ...        ...        ...   
GSE81682_GSM2170276_SRR3560095      0.0  0.000000   0.000000   0.000000   
GSE81682_GSM2170277_SRR3560096      0.0  0.000000   0.000000   0.000000   
GSE81682_GSM2170282_SRR3560101      0.0  0.000000   0.000000   0.000000   
GSE81682_GSM2170284_SRR3560103      0.0  0.000000   0.000000   0.000000   
GSE86929_GSM2310415_SRR4242632      0.0  1.723324   3.385881   3.313841   

                                  gm16430        ly6c2  ...      sfxn2  \
GSE41265_GSM1012788_SRR578581    0.147618   143.128830  ...   0.071343   
GSE41265_GSM1110889_SRR799683    0.000000     0.411305  ...   0.000000   
GSE41265_GSM1110890_SRR799684    1.143765  1041.160156  ...   0.000000   
GSE41265_GSM1110890_SRR799685    0.366185  1108.073120  ...   0.000000   
GSE41265_GSM1110891_SRR799686    1.401121     6.002488  ...   0.061560   
...                                   ...          ...  ...        ...   
GSE81682_GSM2170276_SRR3560095   0.000000     0.000000  ...   0.000000   
GSE81682_GSM2170277_SRR3560096   0.000000   149.344803  ...   8.320028   
GSE81682_GSM2170282_SRR3560101   0.000000     1.261936  ...  10.871357   
GSE81682_GSM2170284_SRR3560103   0.000000     1.559253  ...   0.000000   
GSE86929_GSM2310415_SRR4242632  14.670181    48.153164  ...   0.450814   

                                    hmgn3     hist2h4  d630023f18rik  \
GSE41265_GSM1012788_SRR578581    0.000000    0.000000       3.517001   
GSE41265_GSM1110889_SRR799683   73.731819  237.786484       0.000000   
GSE41265_GSM1110890_SRR799684   66.840599    0.000000       0.000000   
GSE41265_GSM1110890_SRR799685   58.001755    0.545156       0.000000   
GSE41265_GSM1110891_SRR799686    0.258660    0.379257       0.000000   
...                                   ...         ...            ...   
GSE81682_GSM2170276_SRR3560095   0.000000    0.000000       0.000000   
GSE81682_GSM2170277_SRR3560096   0.794516    0.000000       0.000000   
GSE81682_GSM2170282_SRR3560101   0.000000    0.000000       0.000000   
GSE81682_GSM2170284_SRR3560103   2.687660    0.000000       2.102183   
GSE86929_GSM2310415_SRR4242632  27.035547    0.000000       2.424400   

                                   efhd1        pid1      myl9        clp1  \
GSE41265_GSM1012788_SRR578581   0.000000   36.010815  0.000000  104.556000   
GSE41265_GSM1110889_SRR799683   0.000000    0.869048  0.000000   30.023003   
GSE41265_GSM1110890_SRR799684   0.736528   54.230759  0.000000    0.046113   
GSE41265_GSM1110890_SRR799685   0.117902   61.593025  0.000000    0.066436   
GSE41265_GSM1110891_SRR799686   0.082023  425.9567

In [40]:
df_concat=pd.concat([df_TF,HvgsData],axis=1)
df_concat

bcl6       stat1      nr3c1       rela  \
GSE41265_GSM1012788_SRR578581   0.000000   10.533667   0.720656  52.959586   
GSE41265_GSM1110889_SRR799683   0.000000  115.562026   4.022323  15.976900   
GSE41265_GSM1110890_SRR799684   0.000000   82.062006   0.074450  15.472971   
GSE41265_GSM1110890_SRR799685   0.000000   82.770504   0.035754  18.050859   
GSE41265_GSM1110891_SRR799686   0.473802  178.210528   5.347746   7.772105   
...                                  ...         ...        ...        ...   
GSE81682_GSM2170276_SRR3560095  0.000000   19.161209   8.821797  29.135278   
GSE81682_GSM2170277_SRR3560096  1.112924    4.437966   6.952604  17.462876   
GSE81682_GSM2170282_SRR3560101  0.000000    6.406364  20.289445  16.339727   
GSE81682_GSM2170284_SRR3560103  0.000000    0.272956  32.047876  43.369873   
GSE86929_GSM2310415_SRR4242632  0.742189    1.311642   2.218930   2.084062   

                                    foxo3      ncor2       ncor1      stat6  \
GSE41265_GSM1012788_SRR578581    0.000000  10.799669    5.905564   0.274156   
GSE41265_GSM1110889_SRR799683    0.000000   0.000000    0.186224  28.853214   
GSE41265_GSM1110890_SRR799684    0.000000   0.000000    5.626441  23.437019   
GSE41265_GSM1110890_SRR799685    0.000000   0.000000    4.590178  25.740975   
GSE41265_GSM1110891_SRR799686    2.543766   0.026324   22.081445   4.660235   
...                                   ...        ...         ...        ...   
GSE81682_GSM2170276_SRR3560095   2.934933   0.939504   92.297315   0.316607   
GSE81682_GSM2170277_SRR3560096   0.449057   1.724979  231.028485  14.532668   
GSE81682_GSM2170282_SRR3560101   0.983522   0.000000   90.274969   4.177601   
GSE81682_GSM2170284_SRR3560103  16.709594   2.461722   45.182407   0.491606   
GSE86929_GSM2310415_SRR4242632   1.245789   0.070100   42.247159   1.007925   

                                     junb      stat2  ...      sfxn2  \
GSE41265_GSM1012788_SRR578581    0.066100  28.249785  ...   0.071343   
GSE41265_GSM1110889_SRR799683   10.473955  36.790521  ...   0.000000   
GSE41265_GSM1110890_SRR799684   11.893267  21.491949  ...   0.000000   
GSE41265_GSM1110890_SRR799685   11.559791  23.307614  ...   0.000000   
GSE41265_GSM1110891_SRR799686   15.228411  21.154344  ...   0.061560   
...                                   ...        ...  ...        ...   
GSE81682_GSM2170276_SRR3560095   3.816737   0.287437  ...   0.000000   
GSE81682_GSM2170277_SRR3560096   9.110043   0.065969  ...   8.320028   
GSE81682_GSM2170282_SRR3560101   6.714868   0.000000  ...  10.871357   
GSE81682_GSM2170284_SRR3560103   0.000000   0.669468  ...   0.000000   
GSE86929_GSM2310415_SRR4242632   0.721445   1.558462  ...   0.450814   

                                    hmgn3     hist2h4  d630023f18rik  \
GSE41265_GSM1012788_SRR578581    0.000000    0.000000       3.517001   
GSE41265_GSM1110889_SRR799683   73.731819  237.786484       0.000000   
GSE41265_GSM1110890_SRR799684   66.840599    0.000000       0.000000   
GSE41265_GSM1110890_SRR799685   58.001755    0.545156       0.000000   
GSE41265_GSM1110891_SRR799686    0.258660    0.379257       0.000000   
...                                   ...         ...            ...   
GSE81682_GSM2170276_SRR3560095   0.000000    0.000000       0.000000   
GSE81682_GSM2170277_SRR3560096   0.794516    0.000000       0.000000   
GSE81682_GSM2170282_SRR3560101   0.000000    0.000000       0.000000   
GSE81682_GSM2170284_SRR3560103   2.687660    0.000000       2.102183   
GSE86929_GSM2310415_SRR4242632  27.035547    0.000000       2.424400   

                                   efhd1        pid1      myl9        clp1  \
GSE41265_GSM1012788_SRR578581   0.000000   36.010815  0.000000  104.556000   
GSE41265_GSM1110889_SRR799683   0.000000    0.869048  0.000000   30.023003   
GSE41265_GSM1110890_SRR799684   0.736528   54.230759  0.000000    0.046113   
GSE41265_GSM1110890_SRR799685   0.117902   61.593025  0.000000    0.066436   
GSE41265_GSM1110891_SRR799686 

In [41]:
from pandas import DataFrame
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.neighbors import NearestNeighbors
from collections import Counter
from scipy.spatial.distance import pdist, squareform

In [44]:
Genexp=df_concat
Genexp_mat=np.mat(df_concat)
pca=PCA(n_components=0.95,svd_solver='full')#实例化
pca.fit(Genexp)#拟合模型
pca_reduction=pca.transform(Genexp)#获取降维后新数据
pca_reduction.shape
nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(pca_reduction)
distances, indices = nbrs.kneighbors(pca_reduction)

scaler = preprocessing.StandardScaler().fit(pca_reduction)
pca_reduction_scaled = scaler.transform(pca_reduction)


In [45]:
pca_reduction_scaled.shape


(6283, 14)

In [46]:

labels=['factor'+str(x) for x in range(0,pca_reduction_scaled.shape[1])]
df_one=DataFrame(pca_reduction_scaled)
df_one['lables']='factor'

def Findmax(nparr):
    c=nparr.tolist()
    return c.index(max(c))

for i in range(len(pca_reduction_scaled[0])):
    z=Findmax(pca_reduction_scaled[i])
    df_one.loc[i,'lables']='f('+str(z)+')'
    
#统计每个细胞K个近邻中标记的数量
#得到样本标记因子
maxgene=np.argmax(pca_reduction_scaled,axis=1)+1
maxgene_list=list(maxgene)
indices_list=list(range(pca_reduction_scaled.shape[0]))

dict_x={indices_list[i]:maxgene_list[i] for i in range(pca_reduction_scaled.shape[0])}

data_x=[]
list_x=[]
arr_list_x=[]
value_list=[]
FN=[]

def counter(Array):
    return Counter(arr_list_x)

def presbar(count): 
    plt.style.use('seaborn-darkgrid')
    plt.bar(list(res.keys()), res.values(), width=0.9, color='g')
    plt.ylabel('Number of tags for sample K neighbors')
    plt.xlabel('f('+str(count+1)+')')
    plt.title('FN('+str(count+1)+')')
    plt.xticks(np.arange(1,34))
#     plt.show()
#     return 
#获取向量   
def getvector(dict_y,i):
    vectors=[0]*pca_reduction_scaled.shape[1]
    for keys_k,values_v in dict_y:
        vectors[keys_k-1]=values_v
    FN.append(vectors)
    return 

for i in range(pca_reduction_scaled.shape[0]):
    p1 = {key:value for key, value in dict_x.items() if key in indices[i]}
    value_x=p1.values()
    value_list=list(value_x)
    arr_list_x=np.array(value_list)
    res=counter(value_list)
    getvector(res.items(),i)
    
X=np.mat(FN)
Y = pdist(X, 'cityblock')

# #将浓缩矩阵还原得到距离矩阵
x = squareform(Y)
print('距离矩阵:\n',x)
#设定阈值

Cells_Adj=1/(1+x)

# Threshold_a=4
# SimMat_x=x.copy()
# print('相似性矩阵：\n ',SimMat_x)
# Cells_Adj = np.where(SimMat_x<= Threshold_a, 1, 0) 
Cells_Adj=np.matrix(Cells_Adj)
print(Cells_Adj,type(Cells_Adj))

距离矩阵:
 [[ 0. 20. 20. ... 20. 20. 20.]
 [20.  0. 20. ... 20. 20. 20.]
 [20. 20.  0. ... 20. 20. 20.]
 ...
 [20. 20. 20. ...  0. 16. 14.]
 [20. 20. 20. ... 16.  0. 14.]
 [20. 20. 20. ... 14. 14.  0.]]
[[1.         0.04761905 0.04761905 ... 0.04761905 0.04761905 0.04761905]
 [0.04761905 1.         0.04761905 ... 0.04761905 0.04761905 0.04761905]
 [0.04761905 0.04761905 1.         ... 0.04761905 0.04761905 0.04761905]
 ...
 [0.04761905 0.04761905 0.04761905 ... 1.         0.05882353 0.06666667]
 [0.04761905 0.04761905 0.04761905 ... 0.05882353 1.         0.06666667]
 [0.04761905 0.04761905 0.04761905 ... 0.06666667 0.06666667 1.        ]] <class 'numpy.matrix'>


In [47]:

#对原始表达数据做scale
min_max_scaler = preprocessing.MinMaxScaler()
gene_exp_minmax = min_max_scaler.fit_transform(df_concat)
gene_df=pd.DataFrame(gene_exp_minmax)
# print('scale后的数据: \n',gene_df)

vectors=[]
for k in range(df_concat.shape[1]):
    var=gene_df[k].value_counts(bins=32,sort=False)
    vectors.append(var.values)

Y_c = pdist(np.mat(vectors), 'cityblock')

t = squareform(Y_c)
# print('距离矩阵:\n ',t)
Genes_Adj=1/(1+t)

# #阈值
# Threshold_b=100

# #邻接矩阵 
# Genes_Adj = np.where(t <= Threshold_b, 1, 0)
Genes_Adj=np.matrix(Genes_Adj)
# print('Gene adjacency matrix：\n',Genes_Adj,type(Genes_Adj),Genes_Adj.shape)
print('相似度矩阵',Genes_Adj)


相似度矩阵 [[1.00000000e+00 3.02206105e-04 1.03412616e-03 ... 1.58478605e-03
  1.12485939e-03 1.01729400e-03]
 [3.02206105e-04 1.00000000e+00 4.20344683e-04 ... 2.54129606e-04
  2.38834488e-04 2.33263354e-04]
 [1.03412616e-03 4.20344683e-04 1.00000000e+00 ... 6.41436818e-04
  5.50357733e-04 5.23286238e-04]
 ...
 [1.58478605e-03 2.54129606e-04 6.41436818e-04 ... 1.00000000e+00
  3.50877193e-03 2.81690141e-03]
 [1.12485939e-03 2.38834488e-04 5.50357733e-04 ... 3.50877193e-03
  1.00000000e+00 9.34579439e-03]
 [1.01729400e-03 2.33263354e-04 5.23286238e-04 ... 2.81690141e-03
  9.34579439e-03 1.00000000e+00]]


In [48]:
Genes_Adj.shape

(1000, 1000)

In [49]:
import scipy.sparse
import sklearn.metrics
import torch
#from torch.autograd import Variable
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
torch.backends.cudnn.benchmark = False
import scipy.sparse as sp
from scipy.sparse import coo_matrix

def setup_seed(seed):
     torch.manual_seed(seed)
     torch.cuda.manual_seed_all(seed)
     np.random.seed(seed)
     torch.backends.cudnn.deterministic = True
# 设置随机数种子
setup_seed(1)
if torch.cuda.is_available():
    print('cuda available')
    dtypeFloat = torch.cuda.FloatTensor
    dtypeLong = torch.cuda.LongTensor
    torch.cuda.manual_seed(1)
else:
    print('cuda not available')
    dtypeFloat = torch.FloatTensor
    dtypeLong = torch.LongTensor
    torch.manual_seed(1)

def sparse_mx_to_torch_sparse_tensor(sparse_mx):
    """Convert a scipy sparse matrix to a torch sparse tensor."""
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(
        np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse.FloatTensor(indices, values, shape)#.requires_grad_()
def load_largesc():
   
    features = df_concat.T
    print(features.shape)
    adjc = Cells_Adj.astype('float32')
    adjg = Genes_Adj.astype('float32')
    print('adjc.shape',adjc.shape)
    
    print('adjg.shape',adjg.shape) 
    return adjc, adjg,np.asarray(features) # cells*genes
                        
adjall_1,adjall_2, alldata = load_largesc()





cuda not available
(1000, 6283)
adjc.shape (6283, 6283)
adjg.shape (1000, 1000)


In [24]:
def high_var_npdata(data, num, cell = None, ind=False): #data: cell * gene  按方差降序排序，选择前num个基因作为分类器的输入此处num=1000
    dat = np.asarray(data)
    datavar = np.var(dat, axis = 0)*(-1)
    ind_maxvar = np.argsort(datavar)
    cell_ind = ind_maxvar[:num]
    if cell is None and ind is False:             
        return data[:, cell_ind]
    if ind:
        return data[:,cell_ind],cell_ind
    return data[:,cell_ind]

def down(alldata,num_cell): #转对数尺度，并进行归一化
#     train_data_all = np.log1p(alldata)
#     maxscale = np.max(train_data_all) 
#     print('maxscale:',maxscale)
#     train_data_all = train_data_all/np.max(train_data_all)  
    train_data_all=alldata
    train_data_all, cellind = high_var_npdata(train_data_all, num= num_cell, ind=1)
#     adj=adjall
    # adj = adjall[cellind,:][:,cellind]
#     adj = adj + sp.eye(adj.shape[0])
    print('load done.')
#     adj = adj/np.max(adj)
    # adj = adj.astype('float32')
    print('[# gene, # cell]', train_data_all.shape)    
    return train_data_all

train_all_data1 = down(alldata,6000)
adj1 =Cells_Adj.astype('float32')
adj2 =Genes_Adj.astype('float32')
# train_all_data2, adj2 = down(alldata, adjall_2,1000)






load done.
[# gene, # cell] (2000, 500)


In [50]:
from scipy import sparse
def laplacian(W, normalized=True):
    """Return graph Laplacian"""

    # Degree matrix.
    d = W.sum(axis=0)
    # Laplacian matrix.
    if not normalized:
        D = scipy.sparse.diags(d.A.squeeze(), 0)
        L = D - W
    else:
        d = d + np.spacing(np.array(0, W.dtype))
        d = 1 / np.sqrt(d)
        D = scipy.sparse.diags(d.A.squeeze(), 0)
        I = scipy.sparse.identity(d.size, dtype=W.dtype)
        L = I - D * W * D
#    assert np.abs(L - L.T).mean() < 1e-9
#     assert type(L) is scipy.sparse.csr.csr_matrix
        L = sparse.csr_matrix(L)
    return L
adj2=np.matrix(adj2)
L1 = [laplacian(adjall_1, normalized=True)]
L2 = [laplacian(adjall_2, normalized=True)]



def weight_init(m):
    if isinstance(m, torch.nn.Conv2d) or isinstance(m, torch.nn.Linear):
        torch.nn.init.xavier_uniform_(m.weight)
        if m.bias is not None: 
            m.bias.data.fill_(0.0)

class my_sparse_mm(torch.autograd.Function):
    """
    Implementation of a new autograd function for sparse variables,
    called "my_sparse_mm", by subclassing torch.autograd.Function
    and implementing the forward and backward passes.
    """
  
    def forward(self, W, x):  # W is SPARSE
        self.save_for_backward(W, x)
        y = torch.mm(W, x)
        return y

    def backward(self, grad_output):
        W, x = self.saved_tensors
        grad_input = grad_output.clone()
        grad_input_dL_dW = torch.mm(grad_input, x.t())
        grad_input_dL_dx = torch.mm(W.t(), grad_input )
        return grad_input_dL_dW, grad_input_dL_dx



def rescale_L(L, lmax=2):
    """Rescale Laplacian eigenvalues to [-1,1]"""
    M, M = L.shape
    
    I = scipy.sparse.identity(M, format='csr', dtype=L.dtype)
    L /= lmax * 2
    L -= I
    return L 

def lmax_L(L):
    """Compute largest Laplacian eigenvalue"""
    return scipy.sparse.linalg.eigsh(L, k=1, which='LM', return_eigenvectors=False)[0]

In [52]:
class Graph_GCN(nn.Module):

    def __init__(self, net_parameters):

        print('Graph ConvNet: GCN')

        super(Graph_GCN, self).__init__()

        # parameters
        D_c1, CL1_F, CL1_K,  FC1_F,NN_FC1, NN_FC2,out_dim = net_parameters
        D_nn1 = D_c1
     
        self.in_dim1 = D_c1
        
        self.out_dim = out_dim
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.num_gene = D_nn1
        self.initScale = initScale = 6
        self.poolsize = 15
        FC1Fin1 = CL1_F*(D_c1//self.poolsize)
       
        self.FC1Fin1 = FC1Fin1
       
        self.CL1_K = CL1_K; self.CL1_F = CL1_F; 
        
#         Fin = FC1_F + NN_FC2; Fout = self.out_dim;
#         self.FC_sum2 = nn.Linear(Fin, Fout)     
        # graph CL1

        #      self_cl1为卷积核层，传入图卷积函数中的一个参数
        #      CL1_F = 5
        #      CL1_K = 5
       
        self.cl1 = nn.Linear(CL1_K, CL1_F)
        
                    
        #FC_sum2 with NN
                        
        
        #池化层之后的全连接层
        self.fc1 = nn.Linear(FC1Fin1, FC1_F)
       


        Fin = FC1_F + NN_FC2
        Fout = self.out_dim
        self.FC_sum2 = nn.Linear(Fin, Fout) 
        
#         self.nn_fc1 = nn.Linear(self.in_dim, NN_FC1)
#         # NN_FC2
#         self.nn_fc2 = nn.Linear(NN_FC1, NN_FC2)

    def init_weights(self, W, Fin, Fout):

        scale = np.sqrt( self.initScale / (Fin+Fout) )
        W.uniform_(-scale, scale)
        
        return W

    def graph_conv_cheby(self, x, cl,L, Fout, K):

        # parameters、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、
        # B = batch size
        # V = nb vertices
        # Fin = nb input features
        # Fout = nb output features
        # K = Chebyshev order & support size
        B, V, Fin = x.size(); B, V, Fin = int(B), int(V), int(Fin)
        print('输入graph_conv_cheby的X',x.size())
        # rescale Laplacian
        lmax = lmax_L(L)
        L = rescale_L(L, lmax)
       
        # convert scipy sparse matric L to pytorch
        L = sparse_mx_to_torch_sparse_tensor(L)
        if torch.cuda.is_available():
            L = L.cuda()

        # transform to Chebyshev basis
        x0 = x.permute(1,2,0).contiguous()  # V x Fin x B
        x0 = x0.view([V, Fin*B])            # V x Fin*B
        x = x0.unsqueeze(0)                 # 1 x V x Fin*B

        def concat(x, x_):
            x_ = x_.unsqueeze(0)            # 1 x V x Fin*B
            return torch.cat((x, x_), 0)    # K x V x Fin*B

        if K > 1:
            x1 = my_sparse_mm()
            x1=x1.forward(L,x0)# V x Fin*B
            x = torch.cat((x, x1.unsqueeze(0)),0)  # 2 x V x Fin*B
        for k in range(2, K):
            x2 =my_sparse_mm()
            x2=2*(x2.forward(L,x1))- x0
            x = torch.cat((x, x2.unsqueeze(0)),0)  # M x Fin*B --> K x V x Fin*B
            x0, x1 = x1, x2

        x = x.view([K, V, Fin, B])           # K x V x Fin x B
        x = x.permute(3,1,2,0).contiguous()  # B x V x Fin x K
        x = x.view([B*V, Fin*K])             # B*V x Fin*K

        # Compose linearly Fin features to get Fout features
        x = cl(x)                            # B*V x Fout
        x = x.view([B, V, Fout])             # B x V x Fout
        return x


    # Max pooling of size p. Must be a power of 2.
    def graph_max_pool(self, x, p):
        if p > 1:
            x = x.permute(0,2,1).contiguous()  # x = B x F x V
            x = nn.MaxPool1d(p)(x)             # B x F x V/p
            x = x.permute(0,2,1).contiguous()  # x = B x V/p x F
            return x
        else:
            return x

    def forward(self, x_in, d, L1):
        
        x1 = x_in#[:,:self.num_gene]
        x2 = x_in#[:,self.num_gene:]
        # print(type(x_in))
        # print('进入forward函数的x1',x1.shape)
        x1 = x1.unsqueeze(2) # B x V x Fin=1
        x1 = self.graph_conv_cheby(x1, self.cl1, L1[0], self.CL1_F, self.CL1_K)
        print('graph_conv_cheby后的x1',x1.shape)
        x1 = F.relu(x1)
        x1 = self.graph_max_pool(x1, self.poolsize)
        print('maxpool后的x1',x1.shape)
        # flatten()
        x1 = x1.view(-1, self.FC1Fin1)
       
        print('flatten后的X1',x1.shape)
        x1 = self.fc1(x1)
        x1 = F.relu(x1)
        x_hidden_gae1 = x1
        
#         print('x_hidden_gae',x_hidden_gae,x_hidden_gae.shape)
        ##############################################
        ##                  GCN1//GCN2             ##
        ##############################################
       
        # x2 = x2.unsqueeze(2) # B x V x Fin=1
        # x2 = self.graph_conv_cheby(x2, self.cl1, L2[0], self.CL1_F, self.CL1_K)
        # print('graph_conv_cheby后的x2',x2.shape)
        # x2 = F.relu(x2)
        # x2 = self.graph_max_pool(x2, self.poolsize)
        # print('maxpool后的x2',x2.shape)
        # # flatten()
        # x2 = x2.view(-1, self.FC1Fin2)
       
        # print('flatten后的X2',x2.shape)
        # x2 = self.fc2(x2)
        # x2 = F.relu(x2)
        # x_hidden_gae2 = x2
        # x = torch.cat((x_hidden_gae1, x_hidden_gae2),1)

        # print('connatenate Layer  cat',x.shape)
        # x = self.FC_sum2(x)

        # print('FC_sum2后的x', type(x), x.shape)
        # x = F.log_softmax(x,dim=1) 
        
        return  x_hidden_gae1

In [54]:
D_c1=6283
D_c2=6283
CL1_F = 4
CL1_K = 4
FC1_F = 256
out_dim=10
NN_FC1 = 256
NN_FC2 = 256
net_parameters=[D_c1, CL1_F, CL1_K, FC1_F,NN_FC1, NN_FC2,out_dim]
net = Graph_GCN(net_parameters)
dropout_value = 0.2
net.apply(weight_init)
if torch.cuda.is_available():
    net.cuda()
print(net)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 
all_batch=torch.FloatTensor(alldata)
all_batch= all_batch.to(device)
out_hidden1= net(all_batch, dropout_value, L1)


Graph ConvNet: GCN
Graph_GCN(
  (cl1): Linear(in_features=4, out_features=4, bias=True)
  (fc1): Linear(in_features=1672, out_features=256, bias=True)
  (FC_sum2): Linear(in_features=512, out_features=10, bias=True)
)
输入graph_conv_cheby的X torch.Size([1000, 6283, 1])
graph_conv_cheby后的x1 torch.Size([1000, 6283, 4])
maxpool后的x1 torch.Size([1000, 418, 4])
flatten后的X1 torch.Size([1000, 1672])


In [56]:
out_hidden=pd.DataFrame(out_hidden1).astype("float")
out_hidden


0           1            2          3            4           5    \
0     21.266811    0.000000    26.204407   0.000000    74.950630    2.233438   
1     22.431946  248.847870     0.000000   0.000000   262.906097   75.331451   
2      0.000000    0.000000     3.123158  53.555393   217.549606  114.092072   
3    291.215271    0.000000     0.000000   0.000000   276.952301   29.780716   
4     15.006101   12.265707    12.479861   0.000000    51.154251   59.174988   
..          ...         ...          ...        ...          ...         ...   
995    0.000000    0.000000  1376.484985   0.000000  3282.656250  938.962524   
996    0.000000   85.235123     0.000000   0.000000    93.862381  140.838379   
997    0.000000    1.901760    98.125679   0.000000   279.068298   94.565361   
998   25.288641    5.017383     0.000000   0.000000     0.000000   14.620335   
999    0.000000    0.000000     0.000000   8.010320     1.598184   10.102810   

             6            7          8           9    ...        246  \
0       0.000000    58.992233   0.000000   25.083899  ...   0.000000   
1     203.838898   165.193344   0.000000    0.000000  ...   0.000000   
2       0.000000   134.847809   0.000000    0.000000  ...   0.000000   
3     127.270340    39.504623   0.000000   65.928001  ...   0.000000   
4      18.192680   155.479523   0.000000    0.000000  ...   0.000000   
..           ...          ...        ...         ...  ...        ...   
995  1646.747314  3534.163330   0.000000  464.023132  ...   0.000000   
996     0.000000   250.279053   0.000000    0.000000  ...   0.000000   
997     0.000000    99.037086  95.590927  268.262756  ...   0.000000   
998     0.000000    74.496460  16.746378    0.000000  ...   0.000000   
999     0.000000    11.243701  26.450413    0.000000  ...  20.517159   

            247         248         249        250         251         252  \
0      0.000000    0.000000   27.808405   0.000000    0.000000    0.000000   
1      0.000000    0.000000   94.040710   0.000000    0.000000    0.000000   
2      0.000000    0.000000  254.490814   0.000000    0.000000  149.401535   
3      0.000000    0.000000  294.402954   0.000000    0.000000    0.000000   
4      0.000000    0.000000   79.783607  23.350712    0.000000    0.000000   
..          ...         ...         ...        ...         ...         ...   
995    0.000000    0.000000  432.405457   0.000000    0.000000    0.000000   
996  164.691803   16.275223  176.674438  64.046715  196.507736  120.919662   
997   90.709358  206.551819  126.374374   0.000000    0.000000  189.533112   
998   51.783928   29.797081   96.783211  29.142441   73.063835    0.000000   
999   10.634785    6.894416    0.000000   7.323568    2.801536   18.108509   

            253        254         255  
0      0.000000  33.980957    0.000000  
1      0.000000   0.000000  111.435089  
2      0.000000   0.000000   33.304695  
3      0.000000   0.000000    0.000000  
4      3.694299   0.000000   82.614311  
..          ...        ...         ...  
995    0.000000   0.000000    0.000000  
996   27.174847   2.912406    0.000000  
997  140.806595   0.000000    0.000000  
998   32.555958   0.000000    0.000000  
999   17.275501   0.000000    0.000000  

[1000 rows x 256 columns]

In [57]:
list1=df_concat.columns.to_list()
out_hidden.index=list1
OutMatrix=out_hidden.T
OutMatrix

bcl6       stat1       nr3c1        rela      foxo3      ncor2  \
0    21.266811   22.431946    0.000000  291.215271  15.006101   1.415743   
1     0.000000  248.847870    0.000000    0.000000  12.265707   0.000000   
2    26.204407    0.000000    3.123158    0.000000  12.479861   0.000000   
3     0.000000    0.000000   53.555393    0.000000   0.000000   0.000000   
4    74.950630  262.906097  217.549606  276.952301  51.154251  20.629738   
..         ...         ...         ...         ...        ...        ...   
251   0.000000    0.000000    0.000000    0.000000   0.000000   0.000000   
252   0.000000    0.000000  149.401535    0.000000   0.000000   0.000000   
253   0.000000    0.000000    0.000000    0.000000   3.694299   4.639925   
254  33.980957    0.000000    0.000000    0.000000   0.000000   9.654789   
255   0.000000  111.435089   33.304695    0.000000  82.614311   3.707530   

          ncor1       stat6        junb       stat2  ...       sfxn2  \
0     46.107971   98.857613    0.000000  112.532272  ...    0.000000   
1      0.000000    0.000000   13.373315  152.400375  ...  229.621521   
2     26.305756    0.000000  197.613419    6.648783  ...    0.000000   
3      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
4    958.880249  266.300690  263.522156  191.735306  ...  347.805939   
..          ...         ...         ...         ...  ...         ...   
251    0.000000    0.000000    0.000000    0.000000  ...   82.063744   
252   92.593559    0.000000   35.275955    0.000000  ...    0.000000   
253    0.000000    0.000000    0.000000    2.222614  ...   82.696404   
254    0.000000    0.000000    0.000000    0.000000  ...    0.000000   
255   18.010010    0.000000    0.000000    0.000000  ...  159.917206   

          hmgn3     hist2h4  d630023f18rik      efhd1         pid1  \
0    742.010925  261.030914       0.000000   0.000000     0.000000   
1    328.484192  106.816727       0.000000   0.000000     0.000000   
2      0.000000    0.000000       0.000000   0.000000  1376.484985   
3      0.000000  119.908485      34.669727   0.000000     0.000000   
4    876.903625   27.961624     162.476105   0.000000  3282.656250   
..          ...         ...            ...        ...          ...   
251    0.000000    0.000000       0.000000   6.687420     0.000000   
252  438.310120   73.345268      53.297577  30.333635     0.000000   
253    0.000000    0.000000       0.000000   0.000000     0.000000   
254    0.000000    0.000000      52.578781   0.000000     0.000000   
255    0.000000    0.000000      40.331944   0.000000     0.000000   

           myl9        clp1     olfml3      kcnc4  
0      0.000000    0.000000  25.288641   0.000000  
1     85.235123    1.901760   5.017383   0.000000  
2      0.000000   98.125679   0.000000   0.000000  
3      0.000000    0.000000   0.000000   8.010320  
4     93.862381  279.068298   0.000000   1.598184  
..          ...         ...        ...        ...  
251  196.507736    0.000000  73.063835   2.801536  
252  120.919662  189.533112   0.000000  18.108509  
253   27.174847  140.806595  32.555958  17.275501  
254    2.912406    0.000000   0.000000   0.000000  
255    0.000000    0.000000   0.000000   0.000000  

[256 rows x 1000 columns]

In [58]:
Zerovalues0=list(OutMatrix.loc[:,(OutMatrix==0).all()].columns)
len(Zerovalues0)

0

In [59]:
DeletedMatrix=OutMatrix.drop(labels=Zerovalues0,axis=1)
ScoreMatrix=DeletedMatrix.corr()
ScoreMatrix

bcl6     stat1     nr3c1      rela     foxo3     ncor2     ncor1  \
bcl6    1.000000  0.284238  0.277854  0.317022  0.121943  0.116059  0.375875   
stat1   0.284238  1.000000  0.406639  0.470275  0.264672  0.220135  0.413030   
nr3c1   0.277854  0.406639  1.000000  0.460372  0.322731  0.335434  0.600827   
rela    0.317022  0.470275  0.460372  1.000000  0.249825  0.285541  0.470171   
foxo3   0.121943  0.264672  0.322731  0.249825  1.000000  0.203628  0.387801   
...          ...       ...       ...       ...       ...       ...       ...   
pid1    0.452861  0.442440  0.344994  0.433437  0.208212  0.080410  0.366887   
myl9   -0.093338  0.092765 -0.002917 -0.028111  0.154109  0.133048  0.042918   
clp1    0.050742  0.212256  0.265632  0.274198  0.252952  0.135960  0.241134   
olfml3 -0.018072  0.152709  0.070235  0.009149  0.197188  0.108871  0.107365   
kcnc4   0.052613  0.011167  0.009279 -0.068003  0.000661 -0.039563  0.053368   

           stat6      junb     stat2  ...     sfxn2     hmgn3   hist2h4  \
bcl6    0.348574  0.143921  0.271124  ...  0.151602  0.257686  0.117671   
stat1   0.489403  0.431017  0.553319  ...  0.221205  0.435620  0.146166   
nr3c1   0.511313  0.479937  0.453177  ...  0.135244  0.329132  0.142584   
rela    0.646275  0.441431  0.577917  ...  0.148063  0.399033  0.051700   
foxo3   0.293247  0.297020  0.243056  ...  0.140484  0.384847  0.066816   
...          ...       ...       ...  ...       ...       ...       ...   
pid1    0.372948  0.252556  0.455081  ...  0.152450  0.315511  0.066783   
myl9   -0.118698 -0.009674 -0.032605  ...  0.033664  0.133256 -0.043177   
clp1    0.210663  0.247337  0.283591  ...  0.061893  0.186491  0.006429   
olfml3 -0.071779  0.042644  0.042233  ... -0.045335  0.158671  0.104047   
kcnc4  -0.036383 -0.039017 -0.053459  ...  0.005480  0.176627  0.078552   

        d630023f18rik     efhd1      pid1      myl9      clp1    olfml3  \
bcl6         0.030914 -0.034880  0.452861 -0.093338  0.050742 -0.018072   
stat1        0.149778  0.116898  0.442440  0.092765  0.212256  0.152709   
nr3c1        0.123563  0.053912  0.344994 -0.002917  0.265632  0.070235   
rela         0.064080  0.108362  0.433437 -0.028111  0.274198  0.009149   
foxo3       -0.047310  0.167563  0.208212  0.154109  0.252952  0.197188   
...               ...       ...       ...       ...       ...       ...   
pid1         0.085711  0.036145  1.000000 -0.003156  0.177530  0.038646   
myl9         0.071322 -0.007420 -0.003156  1.000000 -0.043351  0.741248   
clp1         0.117523  0.117160  0.177530 -0.043351  1.000000  0.016529   
olfml3       0.053169  0.009654  0.038646  0.741248  0.016529  1.000000   
kcnc4        0.423391 -0.019113  0.057404  0.059131  0.012464  0.000894   

           kcnc4  
bcl6    0.052613  
stat1   0.011167  
nr3c1   0.009279  
rela   -0.068003  
foxo3   0.000661  
...          ...  
pid1    0.057404  
myl9    0.059131  
clp1    0.012464  
olfml3  0.000894  
kcnc4   1.000000  

[1000 rows x 1000 columns]

In [64]:

S1=Gene_pair_True['geneA'].unique().tolist()
S=[]
for i in range(len(S1)):
    if(S1[i] in df_concat.columns.to_list()):
        S.append(S1[i])
S

['bcl6',
 'stat1',
 'nr3c1',
 'rela',
 'foxo3',
 'ncor2',
 'ncor1',
 'stat6',
 'junb',
 'stat2',
 'srf',
 'smad3',
 'mafb']

In [65]:
TotalMatrix=ScoreMatrix.loc[S]
TotalMatrix

bcl6     stat1     nr3c1      rela     foxo3     ncor2     ncor1  \
bcl6   1.000000  0.284238  0.277854  0.317022  0.121943  0.116059  0.375875   
stat1  0.284238  1.000000  0.406639  0.470275  0.264672  0.220135  0.413030   
nr3c1  0.277854  0.406639  1.000000  0.460372  0.322731  0.335434  0.600827   
rela   0.317022  0.470275  0.460372  1.000000  0.249825  0.285541  0.470171   
foxo3  0.121943  0.264672  0.322731  0.249825  1.000000  0.203628  0.387801   
ncor2  0.116059  0.220135  0.335434  0.285541  0.203628  1.000000  0.362074   
ncor1  0.375875  0.413030  0.600827  0.470171  0.387801  0.362074  1.000000   
stat6  0.348574  0.489403  0.511313  0.646275  0.293247  0.365449  0.522738   
junb   0.143921  0.431017  0.479937  0.441431  0.297020  0.264398  0.390394   
stat2  0.271124  0.553319  0.453177  0.577917  0.243056  0.195014  0.447916   
srf    0.183583  0.271096  0.394664  0.379068  0.289822  0.110120  0.288013   
smad3  0.100262  0.165083  0.257362  0.144738  0.252357  0.305364  0.272628   
mafb   0.235220  0.162837  0.240413  0.218846  0.306362  0.243593  0.297457   

          stat6      junb     stat2  ...     sfxn2     hmgn3   hist2h4  \
bcl6   0.348574  0.143921  0.271124  ...  0.151602  0.257686  0.117671   
stat1  0.489403  0.431017  0.553319  ...  0.221205  0.435620  0.146166   
nr3c1  0.511313  0.479937  0.453177  ...  0.135244  0.329132  0.142584   
rela   0.646275  0.441431  0.577917  ...  0.148063  0.399033  0.051700   
foxo3  0.293247  0.297020  0.243056  ...  0.140484  0.384847  0.066816   
ncor2  0.365449  0.264398  0.195014  ...  0.150658  0.250639 -0.032468   
ncor1  0.522738  0.390394  0.447916  ...  0.147991  0.326752  0.143900   
stat6  1.000000  0.509129  0.521482  ...  0.116899  0.334501  0.009265   
junb   0.509129  1.000000  0.382194  ...  0.083980  0.360197  0.069902   
stat2  0.521482  0.382194  1.000000  ...  0.198198  0.444124  0.154118   
srf    0.365686  0.293506  0.297453  ...  0.033237  0.212781  0.154360   
smad3  0.230908  0.203144  0.110609  ... -0.036628  0.093476  0.038233   
mafb   0.295968  0.251341  0.210389  ...  0.005007  0.315966 -0.052703   

       d630023f18rik     efhd1      pid1      myl9      clp1    olfml3  \
bcl6        0.030914 -0.034880  0.452861 -0.093338  0.050742 -0.018072   
stat1       0.149778  0.116898  0.442440  0.092765  0.212256  0.152709   
nr3c1       0.123563  0.053912  0.344994 -0.002917  0.265632  0.070235   
rela        0.064080  0.108362  0.433437 -0.028111  0.274198  0.009149   
foxo3      -0.047310  0.167563  0.208212  0.154109  0.252952  0.197188   
ncor2       0.145368  0.042795  0.080410  0.133048  0.135960  0.108871   
ncor1       0.187797 -0.038523  0.366887  0.042918  0.241134  0.107365   
stat6       0.090728  0.041775  0.372948 -0.118698  0.210663 -0.071779   
junb        0.050021  0.113965  0.252556 -0.009674  0.247337  0.042644   
stat2       0.149885  0.213452  0.455081 -0.032605  0.283591  0.042233   
srf        -0.015540  0.053454  0.200586  0.017637  0.196716  0.114616   
smad3      -0.001865 -0.003347 -0.010232  0.013913  0.175638  0.102797   
mafb        0.097161  0.088774  0.208077 -0.023101  0.080872 -0.058464   

          kcnc4  
bcl6   0.052613  
stat1  0.011167  
nr3c1  0.009279  
rela  -0.068003  
foxo3  0.000661  
ncor2 -0.039563  
ncor1  0.053368  
stat6 -0.036383  
junb  -0.039017  
stat2 -0.053459  
srf   -0.046006  
smad3 -0.068074  
mafb   0.127710  

[13 rows x 1000 columns]

In [66]:
gene_pair_result =pd.DataFrame(columns=('geneA','geneB','value'))
gene1_name=[]
gene2_name=TotalMatrix.columns.to_list()*len(TotalMatrix.index)
valueTL=[]
for i in range(len(TotalMatrix.index)):
    valueTL+=TotalMatrix.iloc[i].to_list()
for s in S:
    gene1_name+=[s]*len(TotalMatrix.columns)
gene_pair_result['geneA'] = gene1_name
gene_pair_result['geneB'] = gene2_name
gene_pair_result['value'] = valueTL

#删除自身重复的关系
gene_pair_result=gene_pair_result[-(gene_pair_result['geneA']==gene_pair_result['geneB'])]
#保留对称矩阵一半元素
gene_pair_result=gene_pair_result.drop_duplicates(['value'],keep='first')
gene_pair_result


geneA   geneB     value
1      bcl6   stat1  0.284238
2      bcl6   nr3c1  0.277854
3      bcl6    rela  0.317022
4      bcl6   foxo3  0.121943
5      bcl6   ncor2  0.116059
...     ...     ...       ...
12995  mafb    pid1  0.208077
12996  mafb    myl9 -0.023101
12997  mafb    clp1  0.080872
12998  mafb  olfml3 -0.058464
12999  mafb   kcnc4  0.127710

[12909 rows x 3 columns]

In [69]:

AfterMerged=pd.merge(gene_pair_result,Gene_pair_True,on=['geneA', 'geneB'],how='outer')

AfterMerged

geneA   geneB   value_x  value_y
0      bcl6   stat1  0.284238      NaN
1      bcl6   nr3c1  0.277854      NaN
2      bcl6    rela  0.317022      NaN
3      bcl6   foxo3  0.121943      NaN
4      bcl6   ncor2  0.116059      NaN
...     ...     ...       ...      ...
64040  mafb   cenpl       NaN      0.0
64041  mafb    cd86       NaN      1.0
64042  mafb     prn       NaN      1.0
64043  mafb   ubtd2       NaN      0.0
64044  mafb  inpp5a       NaN      1.0

[64045 rows x 4 columns]

In [68]:
AfterMerged=AfterMerged.fillna(0)
#AfterMerged

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

AfterMerged['value_x']=AfterMerged.value_x.abs()

value_x_list=AfterMerged['value_x'].to_numpy()
value_y_list=AfterMerged['value_y'].to_numpy()

print(roc_auc_score(value_y_list,value_x_list))

0.36344968122214394


In [70]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

FilterNaN=AfterMerged[~AfterMerged.isna().any(axis=1)]
# FilterNaN
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

FilterNaN['value_x']=FilterNaN.value_x.abs()

value_x_list=FilterNaN['value_x'].to_numpy()
value_y_list=FilterNaN['value_y'].to_numpy()

print(roc_auc_score(value_y_list,value_x_list))

0.6691169920019007


/tmp/ipykernel_269028/3706404322.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FilterNaN['value_x']=FilterNaN.value_x.abs()


In [ ]:
from sklearn.metrics import roc_curve 
from sklearn.metrics import roc_auc_score as AUC


# 利用roc_curve函数获得假阳性率FPR，和真阳性率recall，都是一系列值
FPR, recall, thresholds = roc_curve(FilterNaN["value_y"],FilterNaN["value_x"])
# 计算AUC面积
area = AUC(FilterNaN["value_y"],FilterNaN["value_x"])

# 画图
plt.figure()
plt.plot(FPR,recall,label='ROC curve (area = %0.2f)' % area)
plt.legend(loc="lower right")
plt.show()